# Generated by Django 3.1.7 on 2021-06-27 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='purchase_info',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='payment_info', to='my_payments.purchase'),
            preserve_default=False,
        ),
    ]
