# Generated by Django 3.1.7 on 2021-06-27 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_auto_20210502_1012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': [('delete_other_comments', 'Puede eliminar comentarios ajenos'), ('edit_other_comments', 'Puede editar comentarios ajenos')]},
        ),
    ]
