# Generated by Django 3.1.7 on 2021-04-12 00:19

from django.db import migrations, models
import gdstorage.storage
import shopping.models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_1',
            field=models.ImageField(null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to=shopping.models.product_image_path),
        ),
    ]
