# Generated by Django 3.1.7 on 2021-04-06 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='direccion',
            new_name='address',
        ),
    ]
