# Generated by Django 3.1.7 on 2021-03-16 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Nombre_Categoria', max_length=30)),
                ('descripcion', models.TextField(default='Descripcion_Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Nombre_Sucursal', max_length=40)),
                ('direccion', models.CharField(default='Direccion_Sucursal', max_length=60)),
                ('colonia', models.CharField(default='Colonia_Sucursal', max_length=40)),
                ('codigo_postal', models.CharField(default='27123', max_length=10)),
                ('telefono', models.CharField(default='8711234567', max_length=15)),
                ('email', models.EmailField(default='mymail@bakery.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Nombre_Producto', max_length=30)),
                ('descripcion', models.TextField(default='Descripcion_Producto')),
                ('imagen_1', models.ImageField(null=True, upload_to='models/producto/images')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopping.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(default='Detalle_Presentacion', max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.producto')),
            ],
        ),
    ]
