# Generated by Django 3.1.7 on 2021-04-12 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20210412_0019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_1',
            new_name='image',
        ),
    ]
