# Generated by Django 3.1.7 on 2021-04-17 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_auto_20210412_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpresentation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='shopping.product'),
        ),
    ]
