# Generated by Django 3.1.7 on 2021-04-20 18:37

from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage
import shopping.models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_auto_20210417_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopping.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to=shopping.models.product_image_path),
        ),
    ]
