# Generated by Django 3.1.7 on 2021-06-26 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='presentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopping.productpresentation'),
        ),
        migrations.AlterField(
            model_name='productpresentation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presentations', to='shopping.product'),
        ),
    ]
